### ISSUE TITLE
Impute_date discrepancy

### ISSUE THREAD

**Issue by andersonjake1988** [Gilead-BioStats/clindata#166]
When going through function in clindata and checking what the functions do and where they are used I noticed a discrepancy with the impute_date function. @samussiah @mattroumaya 

impute_date essentially just converts a character string to a date if possible, (when only year is input it will return first month and first day, when only year and month are input it will return first day of the month, if it is missing it will give NA), but the cases that this function does anything are actually pretty sparse. I combined all the data tables that impute_date was used on and it has 1,477,678 entries of those only 142 have a date that is formatted in a way that would be captured with impute_date, yet there  are 4,736 data points that are numerically formatted dates that are not captured by this function, and instead return NA. 

I propose a change to impute date to add logic for convertind numerical date values to date while preserving the logic from the previous function. 

new version
```
impute_date <- function(date){
                     num_correct <- compose(as.character, as_date, as.numeric)
                     if (lubridate::is.Date(date)) {
                         return(date)
                     } else {
                     as.Date(ifelse(grepl("\\-\\-", date), 
                                    {a <- str_remove_all(date, "\\-\\-")
                                     ifelse(nchar(a) == 7, 
                                            paste0(a, "-01"), 
                                            ifelse(nchar(a) == 4, 
                                                   paste0(a, "-01-01"), 
                                                   NA_character_))},
                                    ifelse(!grepl("\\-", date),
                                            num_correct(date),
                                            NA_character_)))
                   }
}
```

old version
```
impute_date <- function(date) {
  if (lubridate::is.Date(date)) {
    return(date)
  }

  # no year-month-day
  no_ymd <- which(date == "-----")
  date[no_ymd] <- NA_character_

  # no month-day
  no_md <- which(grepl("^\\d{4}----$", date))
  date[no_md] <- sub("----$", "-01-01", date[no_md])

  # no day
  no_d <- which(grepl("^\\d{4}-\\d{2}--$", date))
  date[no_d] <- sub("--$", "-01", date[no_d])

  lubridate::ymd(date)
}

```

**Comment by mattroumaya** [comment]
Closed via #179
